### PR TITLE
Removing reliance on sudo to run admin commands

### PR DESCRIPTION
**Pull request by azafty468**
The jenkins user does not have sudo access in our new environment.  Lets take out these super user privileges as so far they have not been necessary.  I've already stabilized the branch used on the Admin jenkins server.

### CODE REVIEW

**Comment by azafty468** [comment]
Just as an FYI, I've tested this on the new Jenkins box for the email opt-in exporter.  We will revisit these changes when we migrate the course exporter and the rest of the exporter functionality.  I suspect SUDO is not needed at all.  But we will address the problem if we encounter it.

**Review by brianhw — APPROVED** [review]
If it works, that's great!  👍 

By the way, is that the only use of "django_user"?

**Comment by azafty468** [comment]
Yup, it appears to be.  I'll go ahead and remove it from the mocks and take it out of the config files.

**Comment by brianhw** [comment]
Looks good.    (Just don't take it out of the secure repo until the old server is retired. : )

**Comment by brianhw** [comment]
Oh, ignore that last comment.   I didn't remember it was also branched already.

**Pull request merged**
