### PR TITLE
Added credit eligibility. (#21)

### PR DESCRIPTION
**Pull request by dsjen**
@edx/analytics -- This PR brings in https://github.com/edx/edx-analytics-exporter/pull/21 to the production branch.

### CODE REVIEW

**Review by iloveagent57 — APPROVED** [review]

**Comment by brianhw** [comment]
Ah, well.  We normally do --ff-only merges for moving changes from master to release and environment/production.

**Comment by dsjen** [comment]
Oh, sorry for messing up the process. Please let me know if you need me to remove the commit, etc.!

**Comment by brianhw** [comment]
Actually, it would probably be good if it were possible to remove the commit and just merge fast-forward.  We did that once with the pipeline release branch.  Let me know if you need help.

**Comment by dsjen** [comment]
@brianhw - ok, I think I will want to coordinate the commit removal and the fast forward with you. I'll let up a short meeting to get in sync.

**Pull request merged**
