### PR TITLE
Add tasks for exporting course and forum roles.

### PR DESCRIPTION
**Pull request by dianakhuang**
https://openedx.atlassian.net/browse/TNL-4154

@stroilova @brianhw - I'm still working on manually testing this, but I thought it would be useful to give you two a chance to see it in an early form and give me feedback to make sure I'm doing things the correct way / getting the correct infornation.

### CODE REVIEW

**Comment by brianhw** [comment]
I can't comment on whether the information is "correct", but it's the correct way to do things!

**Comment by dianakhuang** [comment]
@catong This is the PR for the new things we're adding to the course packages. Let me know when you want to talk about it.

**Comment by stroilova** [comment]
This looks similar to our overall query, so seems good from my end 👍 

Main difference: this per-course roles export won't include per-Org roles.
This should be OK as only a handful of partners have them set up, and we have not productionalized or advertised them yet.

fyi @mulby  @katymyw

**Comment by stroilova** [comment]
Note: I made an additional question to TNL product about this -- specifically, we should make sure to get definitions for each role & get a TNL product signoff on the roles getting exported.

cc @marcotuts  @sstack22  [TNL-4154](https://openedx.atlassian.net/browse/TNL-4154)

fyi @lamagnifica @katymyw

**Pull request merged**
