### PR TITLE
Add cohort membership to data export

### PR DESCRIPTION
**Pull request by rao-abdul-mannan**
This PR adds course_groups_cohortmembership and course_groups_courseusergroup tables to the database dump (on a per-course basis).

### CODE REVIEW

**Review by azafty468 — COMMENTED** [review]
Yup this is basically what I was expecting.  Pretty straight forward.  The tough part is going to be testing.  I'll update this review to an approved when we can get a file exported

**Review by brianhw — COMMENTED** [review]
I'm not sure the output is quite useful.   That is, you output course_groups_cohortmembership with course_user_group_id, but you don't output course_groups_courseusergroup with an id field so there's no way to look up course_user_group_id in it.  

I see there are two choices.   Either add "id as course_user_group_id" to the select in CourseUserGroupTask, or simply output a single table with a join, so that cohortmemberships is user_id, course_id, group_type, group_name.   It may be good to clarify with requestor if there is a preference.

**Comment by rao-abdul-mannan** [comment]
@brianhw Requester specified the columns they want in the dump so I stuck with it & haven't added/removed any other column.

**Comment by rao-abdul-mannan** [comment]
@azafty468 Course export build has finished successfully.

**Comment by azafty468** [comment]
So how did this succeed?  I was expecting you to hit the same error that Hassan noted.  Did you run on the aed branch?

**Comment by brianhw** [comment]
By the way, this is what I meant by the single table output, in case it's helpful:

```sql
 select cm.user_id, cm.course_id, cug.group_type, cug.name from course_groups_cohortmembership cm join course_groups_courseusergroup cug on cm.course_user_group_id = cug.id where cm.course_id =${course_id}
```

**Comment by rao-abdul-mannan** [comment]
@azafty468 as per our 1-1 discussion on hipchat, I hope I answered your question.

**Comment by rao-abdul-mannan** [comment]
Course exporter job has succeeded.

**Review by azafty468 — APPROVED** [review]
Requestor sign off and job output looks good.  I'm a 👍 on this.  Abdul can you coordinate with Kathleen and ask her how soon she needs this code released?  And if it's possible we could delay it for a few weeks while we work on the other work in the exporter job.

**Comment by rao-abdul-mannan** [comment]
@azafty468 I got update from Kathleen & she said that its acceptable if we can wrap it up by the end of August.

**Pull request merged**
