### PR TITLE
Update edx-opaque-keys.

### PR DESCRIPTION
**Pull request by brianhw**
Use version 0.2.1.

@mulby @HassanJaveed84

### CODE REVIEW

**Comment by brianhw** [comment]
@mulby @HassanJaveed84 This was used for running the latest export.  We were running with a very old version of opaque keys before (that didn't define Locators).  This fixes that issue at least.

**Comment by mulby** [comment]
I'm nervous about people breakout or stuff with new versions of these libraries, would it make sense to pin them to their current versions?

**Comment by brianhw** [comment]
Maybe.  I didn't pin them because nothing else is pinned.

**Comment by brianhw** [comment]
And we run with the release version of prod as well.   Offhand, it seems like we should either pin everything or nothing.

**Comment by mulby** [comment]
ah, fair points. :+1:

**Pull request merged**
